server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: egrevs
    password:
    driver-class-name: org.postgresql.Driver
  #    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml

